name: Reusable WF - Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  pepify:
    uses: "./.github/workflows/pepify.yml"
    with:
      version: ${{ inputs.version }}

  build:
    needs: ["pepify"]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user

    - name: Build a binary wheel and a source tarball
      run: >-
        python3 -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION: ${{ needs.pepify.outputs.pepified-version }}

    - name: Upload Tarball Artifact
      uses: actions/upload-artifact@v3
      with:
        name: howso-visuals-${{ needs.pepify.outputs.pepified-version }}.tar.gz
        path: dist/howso-visuals-${{ needs.pepify.outputs.pepified-version }}.tar.gz
        if-no-files-found: error

    - name: Upload Wheel Artifact
      uses: actions/upload-artifact@v3
      with:
        name: howso_visuals-${{ needs.pepify.outputs.pepified-version }}-py3-none-any.whl
        path: dist/howso_visuals-${{ needs.pepify.outputs.pepified-version }}-py3-none-any.whl
        if-no-files-found: error

  test-3-8:
    needs: ["build"]
    uses: "./.github/workflows/pytest.yml"
    secrets: inherit
    with:
      python-version: "3.8"

  test-3-9:
    needs: ["build"]
    uses: "./.github/workflows/pytest.yml"
    secrets: inherit
    with:
      python-version: "3.9"

  test-3-10:
    needs: ["build"]
    uses: "./.github/workflows/pytest.yml"
    secrets: inherit
    with:
      python-version: "3.10"

  test-3-11:
    needs: ["build"]
    uses: "./.github/workflows/pytest.yml"
    secrets: inherit
    with:
      python-version: "3.11"
